[package]
name = "rendrs"
version = "0.1.0"
authors = ["Trevor Elliott <awesomelyawesome@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
image = "0.21.2"
nalgebra = "0.18.0"
num_cpus = "1.10.1"
yaml-rust = "0.4.3"
failure = "0.1.5"

[[bin]]
name = "rainbow"

[[bin]]
name = "sphere"

[profile.release]
debug = true
