[package]
name = "rendrs"
version = "0.1.0"
authors = ["Trevor Elliott <awesomelyawesome@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
image = "0.21.2"
nalgebra = "0.18.0"
num_cpus = "1.10.1"
failure = "0.1.5"
serde = { version = "1.0.98", features = ["derive"] }
serde_yaml = "0.8.9"
pbr = "1.0.1"

[[bin]]
name = "rendrs"

[profile.release]
debug = true
